//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCliente46
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadastro
    {
        public int Cliente_ID { get; set; }
        public string NomeCliente { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string TelefoneContato { get; set; }
    }
}
